"""initial migration

Revision ID: 0001
Revises: 
Create Date: 2024-08-15 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encabezados_notas',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_solicitante', sa.String(), nullable=False),
    sa.Column('filial', sa.String(), nullable=False),
    sa.Column('almacen', sa.String(), nullable=False),
    sa.Column('centro_costo', sa.String(), nullable=True),
    sa.Column('creado_por', sa.String(), nullable=False),
    sa.Column('firmas_json', JSONB(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encabezados_notas_id'), 'encabezados_notas', ['id'], unique=False)
    op.create_table('detalles_notas_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nota_id', UUID(as_uuid=True), nullable=False),
    sa.Column('linea', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('um', sa.String(), nullable=False),
    sa.Column('factor_empaque', sa.Integer(), nullable=False),
    sa.Column('cantidad_entregada', sa.Integer(), nullable=False),
    sa.Column('cantidad_devuelta', sa.Integer(), server_default='0', nullable=False),
    sa.Column('requiere_lote', sa.Boolean(), nullable=False),
    sa.Column('lote', sa.String(), nullable=True),
    sa.Column('serie', sa.String(), nullable=True),
    sa.Column('empresa_origen', sa.String(), nullable=True),
    sa.Column('intercompany', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('estado_regularizacion', sa.String(), nullable=True),
    sa.Column('sc_numero', sa.String(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('observacion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['nota_id'], ['encabezados_notas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nota_id', 'linea', name='_nota_linea_uc')
    )
    op.create_index(op.f('ix_detalles_notas_items_id'), 'detalles_notas_items', ['id'], unique=False)
    op.create_index(op.f('ix_detalles_notas_items_producto'), 'detalles_notas_items', ['producto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_notas_items_producto'), table_name='detalles_notas_items')
    op.drop_index(op.f('ix_detalles_notas_items_id'), table_name='detalles_notas_items')
    op.drop_table('detalles_notas_items')
    op.drop_index(op.f('ix_encabezados_notas_id'), table_name='encabezados_notas')
    op.drop_table('encabezados_notas')
    # ### end Alembic commands ###
